maven:
  executable: "D:/apps/maven/apache-maven-3.9.9/bin/mvn.cmd"

vars:
  # 本地仓库根目录
  base_path: "D:/document/Github/chainwork"

  # git clone 根路径
  git_base: "http://192.168.4.49/Project/FKS_WMSTMS_PIP"
  repo_suffix: ".git"

  # 默认浅克隆（想关就改成 "false"）
  shallow_default: "true"

  branch_tssb_develop: "tssb_develop"
  branch_Develop: "Develop"
  branch_TMS_Develop: "TMS_Develop"

  output_tssb_develop: "D:/document/Github/chainworkWar/tssb_develop"
  output_Develop: "D:/document/Github/chainworkWar/Develop"

  openapi_path: "${base_path}/openapi"
  apps_path: "${base_path}/apps"

includes:
  - name: apps
    path: "config/apps.yml"
  - name: openapi
    path: "config/openapi.yml"
